version: "2.1"

services:

  web:
    build: .
    container_name: app
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn serviceWithLove.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - ./.env.prod
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
      - /data/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  static_volume:
