version: "2.1"

services:
  db:
    restart: always
    image: postgis/postgis
    container_name: dbwlove
    env_file:
      - ./.env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U owner -d swl"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: app
    command: bash -c "python manage.py migrate && python manage.py loaddata fixtures/full_data_24042021.json && python manage.py collectstatic --no-input && gunicorn serviceWithLove.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - ./.env.prod
    depends_on: 
      db:
        condition: service_healthy
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
      - /data/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  static_volume:
  postgres_data:
