# Generated by Django 3.1.8 on 2021-04-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0003_auto_20210418_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('email', models.CharField(max_length=200, verbose_name='customer email')),
                ('token', models.CharField(max_length=200, verbose_name='stripe token')),
                ('str_customer_id', models.CharField(max_length=200, verbose_name='stripe customer id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('stripe_order_id', models.CharField(max_length=200, verbose_name='stripe order id')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
