# Generated by Django 3.1.7 on 2021-03-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWithLove', '0002_cardservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardservice',
            name='description',
            field=models.TextField(default='Description', max_length=1000),
        ),
    ]
