# Generated by Django 3.1.7 on 2021-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWithLove', '0003_auto_20210326_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardservice',
            name='logo',
            field=models.ImageField(default='', upload_to='logos/'),
            preserve_default=False,
        ),
    ]
