# Generated by Django 3.1.7 on 2021-03-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWithLove', '0004_cardservice_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardservice',
            name='title',
            field=models.TextField(default='Service', max_length=50),
        ),
    ]
