# Generated by Django 3.1.7 on 2021-04-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWithLove', '0005_auto_20210326_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardservice',
            name='template',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=255, verbose_name='Template'),
        ),
    ]
