# Generated by Django 3.1.7 on 2021-04-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('serviceWithLove', '0006_cardservice_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCleaning',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='servicewithlove_cardcleaning', serialize=False, to='cms.cmsplugin')),
                ('title', models.TextField(default='Title', max_length=50)),
                ('items', models.TextField(default='Items', max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('template', models.CharField(choices=[('cleaning/card_img_left.html', 'Cleaning Image Left'), ('cleaning/card_img_right.html', 'Cleaning Image Right'), ('organizing/card_img_left.html', 'Organizing Image Left'), ('organizing/card_img_right.html', 'Organizing Image Right'), ('decorating/card_img_right.html', 'Decorating Image Right'), ('cleaning/card_without_logo_left.html', 'Cleaning Without Logo Left'), ('cleaning/card_without_logo_right.html', 'Cleaning Without Logo Right')], default='cleaning/card_img_left.html', max_length=255, verbose_name='Template')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='cardservice',
            name='template',
            field=models.CharField(choices=[('cleaning/card_img_left.html', 'Cleaning Image Left'), ('cleaning/card_img_right.html', 'Cleaning Image Right'), ('organizing/card_img_left.html', 'Organizing Image Left'), ('organizing/card_img_right.html', 'Organizing Image Right'), ('decorating/card_img_right.html', 'Decorating Image Right'), ('cleaning/card_without_logo_left.html', 'Cleaning Without Logo Left'), ('cleaning/card_without_logo_right.html', 'Cleaning Without Logo Right')], default='cleaning/card_img_left.html', max_length=255, verbose_name='Template'),
        ),
    ]
