# Generated by Django 3.1.8 on 2021-04-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWithLove', '0007_auto_20210405_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardservice',
            name='description',
            field=models.TextField(default='Description', max_length=2000),
        ),
    ]
