# Generated by Django 3.1.8 on 2021-04-08 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('region', models.CharField(max_length=100, null=True, verbose_name='region')),
                ('alpha2', models.CharField(max_length=2, verbose_name='alpha2')),
                ('alpha3', models.CharField(max_length=3, verbose_name='alpha3')),
                ('numeric', models.CharField(max_length=4, verbose_name='numeric')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active?')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=2, verbose_name='code')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active?')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoinfo.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active?')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoinfo.state')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
