# Generated by Django 3.1.8 on 2021-04-13 01:51

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estimated_time',
            field=models.IntegerField(default=0, verbose_name='Total estimated time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(validators=[booking.validators.validate_date_greater], verbose_name='date'),
        ),
    ]
