# Generated by Django 3.1.8 on 2021-04-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210412_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bathroom',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='discount',
        ),
    ]
