# Generated by Django 3.1.8 on 2021-04-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210418_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('stripe_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('last_status', models.CharField(max_length=50, verbose_name='last status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.appointment', verbose_name='Appointment_id')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('stripe_status', models.CharField(max_length=50, verbose_name='Stripe status')),
                ('stripe_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.charge', verbose_name='Stripe id')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
