# Generated by Django 3.1.8 on 2021-04-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_chargehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargehistory',
            options={'ordering': ['created_at']},
        ),
    ]
