# Generated by Django 3.1.8 on 2021-04-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210422_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datetimedisabler',
            options={'ordering': ['-from_date']},
        ),
        migrations.RemoveField(
            model_name='cleaningtype',
            name='price',
        ),
        migrations.CreateModel(
            name='CleaningTypePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('price', models.IntegerField(verbose_name='cleaning price')),
                ('cleaning_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.cleaningtype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.servicearea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cleaningtype',
            name='price',
            field=models.ManyToManyField(through='booking.CleaningTypePrice', to='booking.ServiceArea'),
        ),
    ]
