# Generated by Django 3.1.8 on 2021-04-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210424_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaningtype',
            old_name='price',
            new_name='service_area',
        ),
    ]
