# Generated by Django 3.1.8 on 2021-04-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210424_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningtypeprice',
            options={'ordering': ['service']},
        ),
        migrations.AddField(
            model_name='cleaningtype',
            name='price',
            field=models.IntegerField(default=0, verbose_name='cleaning price'),
            preserve_default=False,
        ),
    ]
