# Generated by Django 3.1.8 on 2021-04-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20210424_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningtype',
            name='price',
        ),
    ]
