# Generated by Django 3.1.8 on 2021-04-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_cleaningtype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
    ]
