# Generated by Django 3.1.8 on 2021-04-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210424_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='country',
        ),
    ]
