# Generated by Django 3.1.8 on 2021-04-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_appointment_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningtype',
            options={'ordering': ['id']},
        ),
    ]
